manual.html: manual.xml
#	xsltproc -o manual.html /usr/share/xml/docbook/stylesheet/nwalsh/xhtml/docbook.xsl manual.xml
	xsltproc -o manual.html /usr/share/xml/docbook/xhtml-1_1/docbook.xsl manual.xml
